### ISSUE TITLE
Configuration under Windows 10

### ISSUE THREAD

**Issue by webfolderio** [mgzme/MAME-PSGS#1]
Hi, unable to use your CRT filter.

* i created **glsl** directory
* i have copied **mame-psgs.vsh** and **mame-psgs_rgb32_dir.fsh** to **glsl** directory
* i created **custom_crt.vsh** and set palette_emulation value

Could you please help me to apply your crt filter mame?

Thanks

*Mame version 0.208, OS: Windows 10*

**Comment by TheCodeTherapy** [comment]
@webfolderio I don't understand what you mean by creating a custom_crt.vsh

Custom palettes should be added with the rest of them in the `mame-psgs_rgb32_dir.fsh` shader.
