### ISSUE TITLE
Works in MacOS with a different path designation

### ISSUE THREAD

**Issue by estefan3112** [mgzme/MAME-PSGS#2]
Hi, great work, at least in MacOS, the path to glsl_shader_mame0 must be different: 
/Users/---insert username---/---insert path to mame folder---/mame/glsl/mame-psgs
And great performance as a lightweight shader!
(MacMini M1 and mame 246)

**Comment by TheCodeTherapy** [comment]
Thank you very much for the info @estefan3112 . I'll add this issue to the README so other users can benefit from the info you provided.
