### ISSUE TITLE
does not work in linux

### ISSUE THREAD

**Issue by B-Nerd** [mgzme/MAME-PSGS#3]
the glsl line looks like this but it does not work
glsl_shader_mame0         "./glsl/mame-psg"
i even did a absolute path it also does nothing
it looks like this
glsl_shader_mame0         "/home/username/.mame/glsl/mame-psgs"

[mame.txt](https://github.com/TheCodeTherapy/MAME-PSGS/files/10334111/mame.txt)
[alien3.txt](https://github.com/TheCodeTherapy/MAME-PSGS/files/10334320/alien3.txt)
here are my ini's with ./ & a absolute path

**Comment by B-Nerd** [comment]
[alien3.txt](https://github.com/TheCodeTherapy/MAME-PSGS/files/10334110/alien3.txt)
[mame.txt](https://github.com/TheCodeTherapy/MAME-PSGS/files/10334111/mame.txt)
here are my ini's with ./ & a absolute path

**Comment by Hechelion** [comment]
you don't have glsl enabled
change
gl_glsl 0
by
gl_glsl 1

**Comment by Vulto** [comment]
Here are some things to check in order to make it run on linux.
Use fullpath in linux format 
 /home/user/.mame/glsl/mame-psgs  **no "quotes"**

- Verify wich mame.ini config your mame is running
 **mame -showconfig**
- run mame within a terminal:
  If mame can read the shaders it will be displayied on terminal.

**Comment by TheCodeTherapy** [comment]
Valuable info provided by @Vulto and @Hechelion . It definitely works on Linux, as it's the OS where I use it.

The lack of further info from @B-Nerd makes me think the configuration issues faced were solved after the tips.

I'll close this for now. Please feel free to submit a new issue in case the problem persists so I can offer further help.
